# Fork-Sync-All funding configuration
# Displayed as a "Sponsor" button on the GitHub repo page.
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

open_collective: fork-sync-all
