#!/usr/bin/env python3
"""Render downstream organization profiles from the canonical profile README."""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path
from typing import Any

import yaml


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_CONFIG = ROOT / "config/profile-readmes.yml"


class ProfileRenderError(RuntimeError):
    """Raised when profile configuration or source content is invalid."""


def load_config(path: Path) -> dict[str, Any]:
    with path.open(encoding="utf-8") as handle:
        config = yaml.safe_load(handle) or {}

    if config.get("schema_version") != 1:
        raise ProfileRenderError("profile config schema_version must be 1")
    if not isinstance(config.get("source"), dict):
        raise ProfileRenderError("profile config requires a source mapping")
    if not isinstance(config.get("destinations"), dict):
        raise ProfileRenderError("profile config requires a destinations mapping")
    return config


def extract_h2_sections(markdown: str) -> dict[str, str]:
    """Return level-two Markdown sections keyed by their heading text."""

    sections: dict[str, list[str]] = {}
    current: str | None = None
    for line in markdown.splitlines():
        match = re.match(r"^##\s+(.+?)\s*$", line)
        if match:
            current = match.group(1)
            sections[current] = [line]
        elif current is not None:
            sections[current].append(line)
    return {name: "\n".join(lines).rstrip() for name, lines in sections.items()}


def source_commit(source_readme: Path) -> str:
    try:
        result = subprocess.run(
            ["git", "-C", str(source_readme.parent), "rev-parse", "HEAD"],
            check=True,
            capture_output=True,
            text=True,
        )
    except (OSError, subprocess.CalledProcessError):
        return "unknown"
    return result.stdout.strip() or "unknown"


def rewrite_relative_links(markdown: str, repository: str, ref: str) -> str:
    base = f"https://github.com/{repository}/blob/{ref}/"
    pattern = re.compile(r"(?P<prefix>!?\[[^\]]*\]\()(?P<target>[^)]+)(?P<suffix>\))")

    def replace(match: re.Match[str]) -> str:
        target = match.group("target")
        if re.match(r"^(?:[a-z]+:|#|/)", target, re.IGNORECASE):
            return match.group(0)
        return f"{match.group('prefix')}{base}{target}{match.group('suffix')}"

    return pattern.sub(replace, markdown)


def require_string(mapping: dict[str, Any], key: str, context: str) -> str:
    value = mapping.get(key)
    if not isinstance(value, str) or not value.strip():
        raise ProfileRenderError(f"{context}.{key} must be a non-empty string")
    return value.strip()


def render_destination(
    key: str,
    destination: dict[str, Any],
    source: dict[str, Any],
    sections: dict[str, str],
    commit: str,
) -> str:
    source_repo = require_string(source, "repository", "source")
    canonical_url = require_string(source, "canonical_url", "source")
    destination_repo = require_string(destination, "repository", f"destinations.{key}")
    title = require_string(destination, "title", f"destinations.{key}")
    tagline = require_string(destination, "tagline", f"destinations.{key}")
    role = require_string(destination, "role", f"destinations.{key}")
    organization_url = require_string(
        destination, "organization_url", f"destinations.{key}"
    )
    gitlab_url = require_string(destination, "gitlab_url", f"destinations.{key}")
    mascot = require_string(
        destination, "mascot_expression", f"destinations.{key}"
    )
    costume = require_string(
        destination, "cosplay_costume", f"destinations.{key}"
    )
    accent = require_string(destination, "accent", f"destinations.{key}")

    inherited = source.get("inherited_sections")
    if not isinstance(inherited, list) or not inherited:
        raise ProfileRenderError("source.inherited_sections must be a non-empty list")

    rendered_sections: list[str] = []
    for heading in inherited:
        if not isinstance(heading, str) or heading not in sections:
            raise ProfileRenderError(f"source README is missing required section: {heading}")
        rendered_sections.append(rewrite_relative_links(sections[heading], source_repo, commit))

    characters_url = f"{canonical_url}/tree/main/characters"
    provenance_url = f"{canonical_url}/blob/main/characters/PROVENANCE.md"
    lines = [
        "<!--",
        "Generated by fork-sync-all/scripts/render-profile-readmes.py.",
        f"Canonical source: {source_repo}@{commit}",
        f"Destination: {destination_repo}",
        "Do not edit this file directly; update the canonical profile or renderer config.",
        "-->",
        "",
        f"# {title}",
        "",
        f"**{tagline}**",
        "",
        f"[Canonical source workspace]({canonical_url}) · ",
        f"[This GitHub organization]({organization_url}) · ",
        f"[GitLab mirror]({gitlab_url})",
        "",
        "## Role in the mirror chain",
        "",
        role,
        "",
        (
            "Changes and issues belong at the canonical source repository unless a "
            "mirror explicitly documents a different contribution path."
        ),
        "",
        rendered_sections[0],
        "",
        rendered_sections[1],
        "",
        rendered_sections[2],
        "",
        "## Mascot and digital cosplay 📖",
        "",
        (
            f"This layer is represented by Relay's **{mascot}** expression and "
            f"Nexus's **{costume}** digital cosplay costume, using a {accent} "
            "accent plus non-color visual cues."
        ),
        "",
        f"[Meet the characters]({characters_url}) · ",
        f"[Creative provenance]({provenance_url})",
        "",
        (
            "> These characters and stories are fictional creative works. They do "
            "not assert real-world affiliations, operations, or identities."
        ),
        "",
        "## Contribute at the source",
        "",
        (
            "Use the issue tracker or pull requests in the corresponding "
            f"[Interested-Deving-1896 source repository]({canonical_url}). Mirror "
            "copies may be force-synchronized from upstream."
        ),
        "",
    ]
    return "\n".join(lines)


def render_all(
    config: dict[str, Any], source_markdown: str, commit: str
) -> dict[str, tuple[str, str]]:
    source = config["source"]
    destinations = config["destinations"]
    sections = extract_h2_sections(source_markdown)
    rendered: dict[str, tuple[str, str]] = {}
    for key, destination in destinations.items():
        if not isinstance(destination, dict):
            raise ProfileRenderError(f"destinations.{key} must be a mapping")
        output_path = require_string(destination, "output_path", f"destinations.{key}")
        rendered[key] = (
            output_path,
            render_destination(key, destination, source, sections, commit),
        )
    return rendered


def write_outputs(output_dir: Path, rendered: dict[str, tuple[str, str]]) -> None:
    for key, (relative_path, content) in rendered.items():
        path = output_dir / key / relative_path
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(path)


def check_outputs(output_dir: Path, rendered: dict[str, tuple[str, str]]) -> bool:
    clean = True
    for key, (relative_path, content) in rendered.items():
        path = output_dir / key / relative_path
        if not path.is_file() or path.read_text(encoding="utf-8") != content:
            print(f"profile drift: {path}", file=sys.stderr)
            clean = False
    return clean


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", type=Path, default=DEFAULT_CONFIG)
    parser.add_argument("--source", type=Path, required=True)
    parser.add_argument("--source-commit")
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument(
        "--check",
        action="store_true",
        help="compare generated content with output-dir instead of writing",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    try:
        config = load_config(args.config)
        source_markdown = args.source.read_text(encoding="utf-8")
        commit = args.source_commit or source_commit(args.source)
        rendered = render_all(config, source_markdown, commit)
        if args.check:
            return 0 if check_outputs(args.output_dir, rendered) else 1
        write_outputs(args.output_dir, rendered)
        return 0
    except (OSError, ProfileRenderError, yaml.YAMLError) as exc:
        print(f"profile render failed: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
